# Exercise the actual native CLI and collective lifecycle, including rank failure.
set(input "${CMAKE_CURRENT_BINARY_DIR}/request-${MODE}.json")
if(MODE MATCHES "^mpi_gpu")
  set(request [=[{"schema_version":2,"operation":"execute","circuit":{"num_qubits":2,"source":"OPENQASM 2.0; qreg q[2]; creg c[2]; x q[0]; measure q->c;"},"execution":{"shots":12,"seed":7},"simulator":{"backend":"distributed_mpi_gpu","options":{"gpu_device":0},"distribution":{"backend":"ex","global_qubits":[1],"mpi_p2p_bits":0}}}]=])
  if(MODE STREQUAL "mpi_gpu_noise")
    string(JSON request SET "${request}" noise [=[{"mode":"pauli","evaluation":"trajectories","realizations":2,"channels":[{"kind":"bit_flip","targets":[0],"probability":1}]}]=])
  elseif(MODE STREQUAL "mpi_gpu_failure")
    string(JSON request SET "${request}" simulator options gpu_device 2147483647)
  endif()
  file(WRITE "${input}" "${request}")
elseif(MODE STREQUAL "failure")
  file(WRITE "${input}" "{\"schema_version\":2,\"operation\":\"unknown\"}")
elseif(MODE STREQUAL "gpu")
  file(WRITE "${input}" [=[{"schema_version":2,"operation":"execute","circuit":{"num_qubits":2,"source":"OPENQASM 2.0; qreg q[2]; creg c[2]; x q[0]; measure q->c;"},"execution":{"shots":12},"simulator":{"backend":"distributed_gpu","distribution":{"backend":"conventional","devices":[0,0],"global_qubits":[1],"flags":17}}}]=])
else()
  file(WRITE "${input}" [=[{"schema_version":2,"operation":"execute","circuit":{"num_qubits":2,"source":"OPENQASM 2.0; qreg q[2]; creg c[2]; x q[0]; measure q->c;"},"execution":{"shots":12}}]=])
endif()
if(MPI_LAUNCHER)
  set(command "${MPI_LAUNCHER}" ${MPI_PREFLAGS} "${MPI_COUNT_FLAG}" 2 "${WORKER}" --framed-result)
else()
  set(command "${WORKER}" --framed-result)
endif()
execute_process(COMMAND ${command} INPUT_FILE "${input}" OUTPUT_VARIABLE output
  ERROR_VARIABLE logs RESULT_VARIABLE status TIMEOUT 30)
string(REGEX MATCHALL "MAESTRO_RESULT_V2 [^\n]+" frames "${output}")
list(LENGTH frames count)
if(NOT count EQUAL 1)
  message(FATAL_ERROR "Expected one result; got ${count}. Status=${status}; ${output}; ${logs}")
endif()
list(GET frames 0 frame)
string(REGEX REPLACE "^MAESTRO_RESULT_V2 " "" result "${frame}")
string(JSON ok GET "${result}" ok)
if(MODE STREQUAL "failure" OR MODE STREQUAL "mpi_gpu_failure")
  if(ok OR status EQUAL 0)
    message(FATAL_ERROR "A failed rank request was reported as successful: ${result}")
  endif()
  if(MODE STREQUAL "mpi_gpu_failure")
    string(JSON code GET "${result}" error code)
    if(NOT code STREQUAL "native_failure")
      message(FATAL_ERROR "Invalid GPU device did not reach the MPI backend: ${result}")
    endif()
  endif()
else()
  if(NOT ok OR NOT status EQUAL 0)
    message(FATAL_ERROR "Native worker failed: ${result}; ${logs}")
  endif()
  set(expected_bits 10)
  if(MODE STREQUAL "mpi_gpu_noise")
    set(expected_bits 00)
  endif()
  string(JSON shots GET "${result}" counts "${expected_bits}")
  if(MODE MATCHES "^mpi_gpu")
    string(JSON backend GET "${result}" execution_metadata backend)
    if(NOT backend STREQUAL "distributed_mpi_gpu")
      message(FATAL_ERROR "MPI GPU request fell back to ${backend}")
    endif()
  endif()
  if(NOT shots EQUAL 12)
    message(FATAL_ERROR "Incorrect collective count aggregation: ${result}")
  endif()
  if(MPI_LAUNCHER)
    string(JSON ranks GET "${result}" mpi ranks)
    if(NOT ranks EQUAL 2)
      message(FATAL_ERROR "Wrong MPI size: ${result}")
    endif()
  endif()
endif()
