name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: maestro-sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # Install Boost and OpenBLAS on macOS runner to ensure cibuildwheel can pick them up
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install boost openblas
          echo "PKG_CONFIG_PATH=$(brew --prefix openblas)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          # Compile Boost locally since manylinux package managers have very old Boost versions missing Boost.JSON
          CIBW_BEFORE_ALL_LINUX: "curl -L https://archives.boost.io/release/1.89.0/source/boost_1_89_0.tar.gz -o boost.tgz && tar -xzf boost.tgz && cd boost_1_89_0 && ./bootstrap.sh && ./b2 -j4 --with-program_options --with-json --with-container --with-serialization install"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_BUILD: "cp310-* cp311-* cp312-*"
          CIBW_SKIP: "*-musllinux_* *i686 *ppc64le *s390x"

      - uses: actions/upload-artifact@v4
        with:
          name: maestro-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload to PyPI
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/qoro-maestro
    permissions:
      id-token: write # Required for trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: maestro-*
          path: dist
          merge-multiple: true

      - name: Publish package distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
